# Introduction to NumPy

In [3]:
import numpy as np

## Reminder About Built-In Documentation

In [4]:
np?

Type:        module
String form: <module 'numpy' from '/home/igor/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        ~/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x

## Understanding Data Types in Python

### A Python List Is More Than Just a List 

In [12]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
type(L[0])

int

In [11]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [16]:
type(L2[0])

str

In [18]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### Fixed-Type Arrays in Python

In [19]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from Python Lists

In [20]:
#integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [21]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [23]:
# nested lists result in multidimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [24]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
# Create a array filled with a linear sequence
# Startig at 0, ending at 20, stepping by 2
# (this is similiar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# Create a array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.55932142, 0.75504065, 0.04256638],
       [0.34594114, 0.04921165, 0.28656742],
       [0.89376482, 0.57432615, 0.65391544]])

In [34]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[-0.69545049,  2.32378115,  0.4427155 ],
       [-0.5385338 , -0.08363375,  0.8107785 ],
       [-0.36755259,  0.30132416, -1.20226265]])

In [39]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3,3))

array([[8, 0, 3],
       [3, 1, 1],
       [7, 1, 1]])

In [41]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
 # Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

### NumPy Standard Data Types

In [45]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [46]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## The Basics of NumPy Arrays

### NumPy Array Attributes

In [48]:
import numpy as np
np.random.seed(0) # seed for reproductbility


x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) #Three-dimensional array

In [49]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [50]:
print("dtype: ", x3.dtype)

dtype:  int64


In [51]:
print("itemsize: ", x3.itemsize, " bytes")
print("nbytes: ", x3.nbytes, " bytes")

itemsize:  8  bytes
nbytes:  480  bytes


### Array Indexing: Accessing Single Elements

In [52]:
x1

array([5, 0, 3, 3, 7, 9])

In [53]:
x1[0]

5

In [54]:
x1[4]

7

In [55]:
x1[-1]

9

In [56]:
x1[-2]

7

In [57]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [58]:
x2[0, 0]

3

In [59]:
x2[2, 0]

1

In [60]:
x2[2, -1]

7

In [61]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [63]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing: Accessing Subarrays

#### One-dimensional subarrays

In [66]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x[:5]

array([0, 1, 2, 3, 4])

In [68]:
x[5:]

array([5, 6, 7, 8, 9])

In [69]:
x[4:7]

array([4, 5, 6])

In [70]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [71]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

#### Multidimensional subarrays

In [72]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [73]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [74]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [75]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [76]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [77]:
print(x2[0, :]) # first row of x2

[12  5  2  4]


In [78]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


#### Subarrays as no-copy views

In [80]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [81]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [82]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [83]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### Creating copies of arrays

In [84]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [85]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [86]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

In [87]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [89]:
 # row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [90]:
# column vector via reshape
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [92]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

#### Concatenation of arrays

In [94]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [96]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3 99 99 99  3  2  1]


In [99]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [100]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [104]:
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6], 
                 [7, 8, 9]])
grid = grid[::-1, ::-1]

In [105]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [108]:
# horizontally stack the arrays
y = np.array([[99], 
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### Splitting of arrays

In [114]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [115]:
grid = np.arange(16).reshape(4, 4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [123]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on NumPy Arrays: Universal Functions

### The Slowness of Loops